import { Platform } from 'react-native';
import { ContentCategory } from './content';

// Android emülatörde localhost yerine 10.0.2.2 kullanılır
const API_BASE =
  Platform.OS === 'android' ? 'http://10.0.2.2:3000' : 'http://localhost:3000';

export interface ApiArticle {
  id: string;
  title: string;
  description: string;
  content?: string;
  url: string;
  imageUrl?: string;
  publishedAt: string;
  source: {
    id?: string;
    name: string;
    url: string;
    type: 'newsapi' | 'rss' | 'scraper';
  };
  category?: string;
  language: string;
}

interface FetchNewsParams {
  language?: 'tr' | 'en';
  category?: string;
  source?: string;
  limit?: number;
  offset?: number;
}

// Backend kategori → Uygulama kategorisi eşleşmesi (sadece özgün kategoriler)
const CATEGORY_MAP: Record<string, ContentCategory> = {
  technology: 'Teknoloji',
  science: 'Teknoloji',
  sports: 'Spor',
  business: 'Ekonomi',
  health: 'Saglik',
  entertainment: 'Magazin',
  politics: 'Siyaset',
  general: 'Ekonomi', // Genel haberler ekonomi'ye yönlendir, Siyaset'e değil
};

// Başlık / açıklama metninden anahtar kelime ile kategori çıkarımı
const CATEGORY_KEYWORDS: Record<ContentCategory, string[]> = {
  Spor: [
    // Türkçe - Futbol
    'futbol', 'futbolcu', 'futbolü', 'futbola',
    'maç', 'maçı', 'maçında', 'maçtan', 'maçlara', 'kupa maçı', 'derbi',
    'gol', 'golü', 'gole', 'golle', 'gollerine', 'penaltı gol', 'hatrick',
    'şampiyon', 'şampiyonluk', 'şampiyonluğu', 'şampiyonluk müsabakası',
    'lig', 'ligde', 'ligi', 'liğin', 'süper lig', 'üst lig', 'lig yapısı',
    'transfer', 'transferde', 'transferler', 'transfer edilen', 'transfer pazarı',
    'futbol kulübü', 'kulüp', 'kulübü', 'kulübe',
    'antrenör', 'antrenörü', 'antrenörler', 'antrenörlerin',
    'hakem', 'hakeme', 'hakem kararı', 'hakem hatası',
    'kaleci', 'kaleciler',
    'lig şampiyonluğu', 'lig müsabakası',
    'sezon', 'sezonda', 'sezonun', 'sezonu',
    'turnuva', 'turnuvada', 'turnuvanın',
    'derbi', 'derbisi', 'derbisinde', 'derbiye',
    'takım', 'takımlar', 'rakip takım',
    'oyuncu', 'oyuncusu', 'oyuncularda', 'oyuncu performansı',
    // Türkçe - Diğer Spor Dalları
    'basketbol', 'basketbolcu', 'basketbola', 'nba', 'euroleague',
    'voleybol', 'voleybolcu', 'voleybol federasyonu', 'voleybolda',
    'tenis', 'tenisçi', 'tennis', 'wimbledon', 'roland garros', 'us open', 'french open',
    'formula', 'f1', 'f1 araç', 'f1 sürücüsü', 'formula 1',
    'yarış', 'yarışçı', 'pilot', 'yarışta', 'yarış arabası',
    'yüzme', 'yüzücü', 'yüzmedeki',
    'güreş', 'güreşçi', 'güreşe', 'güreş müsabakası',
    'boks', 'boksör', 'boksa', 'boks maçı', 'boks müsabakası',
    'atletizm', 'atlet', 'atletlerin',
    'maraton', 'maratonda',
    'olimpiyat', 'olimpiyat oyunları', 'olimpik',
    'badminton', 'pingpong', 'masa tenisi',
    'buz hokeyi', 'buz patenı',
    'kayak', 'kayakçı', 'snowboard',
    'sporcu', 'sporcusu', 'sporcuların', 'sporcu performansı',
    'stadyum', 'stada', 'stadyumda', 'stadyumun',
    'antrenman', 'antrenmanı', 'antrenman tesisi', 'antrenman seansı',
    'seyirci', 'taraftar', 'taraftarlar', 'taraftar reaksiyonu',
    // Türkçe - Spor İçeriği Genel
    'spor', 'sporla', 'sporda', 'spor müsabakası',
    'spor haberleri', 'spor haber',
    'spor kanalı', 'spor yayını', 'spor yayıncılığı',
    'spor spikeri', 'spor yorumcusu',
    'şampiyon', 'madalya', 'ödül', 'madalyalı',
    'fitness', 'gym', 'egzersiz',
    // İngilizce - Futbol
    'football', 'soccer', 'football match', 'football game',
    'player', 'players', 'football player',
    'goal', 'goals', 'score', 'scoring', 'scored',
    'match', 'game', 'gameplay', 'match result',
    'team', 'teams', 'football team', 'rival team', 'squad',
    'coach', 'manager', 'football manager', 'coaching',
    'referee', 'referee decision', 'referee call',
    'league', 'leagues', 'premier league', 'la liga', 'bundesliga', 'serie a',
    'champion', 'championship', 'champions', 'champions league',
    'tournament', 'tournament final', 'cup tournament',
    'transfer', 'transfers', 'transfer market', 'transfer fee',
    'goalkeeper', 'defender', 'midfielder', 'forward', 'striker',
    'season', 'football season', 'season start',
    'penalty', 'penalty kick', 'penalties',
    'game', 'play', 'performance',
    // İngilizce - Diğer Spor Dalları
    'basketball', 'basketball player', 'nba', 'basketball game',
    'volleyball', 'volleyball player', 'volleyball match',
    'tennis', 'tennis player', 'tennis tournament', 'tennis match',
    'cricket', 'cricket match', 'cricket tournaments',
    'baseball', 'baseball game', 'major league baseball',
    'american football', 'nfl', 'football game',
    'hockey', 'ice hockey', 'hockey game',
    'boxing', 'boxer', 'boxing match', 'boxing championship',
    'wrestling', 'wrestler', 'wrestling match',
    'swimming', 'swimmer', 'swimming competition',
    'track and field', 'athlete', 'athletics',
    'olympics', 'olympic', 'olympic games', 'olympic medal',
    'gold medal', 'silver medal', 'bronze medal',
    'marathon', 'marathon runner',
    'formula 1', 'f1', 'f1 racing', 'f1 driver',
    'racing', 'race', 'race car', 'race driver',
    'sports', 'sport', 'sporting',
    'athlete', 'athletes',
    'competition', 'competitions', 'competing',
    'stadium', 'stadiums', 'arena',
    'training', 'workout', 'gym',
    'fan', 'fans', 'fans react',
    // Almanca - Fußball
    'fußball', 'fußballspieler', 'fußballspiel',
    'tor', 'tore', 'torschuss', 'torwart',
    'spieler', 'spielern', 'spielerleistung',
    'mannschaft', 'mannschaften', 'rivale',
    'trainer', 'trainerin', 'managertrainer', 'training',
    'schiedsrichter', 'schiedsrichterentscheidung',
    'liga', 'bundesliga', 'fußballliga',
    'pokal', 'pokalfinale', 'pokturnier',
    'meister', 'meisterschaft', 'champions league',
    'saison', 'fußballsaison',
    'torverhältnis',
    // Almanca - Andere Sportarten
    'basketball', 'basketballspieler', 'basketball-spiel',
    'volleyball', 'volleyballspieler', 'volleyballspiel',
    'tennis', 'tennisspieler', 'tennisplatz',
    'cricket', 'cricketspiel', 'cricketturnier',
    'baseball', 'baseballspiel', 'major league baseball',
    'american football', 'nfl', 'footballspiel',
    'eishockey', 'hockeyspieler', 'hockeyspiel',
    'boxen', 'boxer', 'boxkampf', 'boxmeisterschaft',
    'ringen', 'ringer', 'ringkampf',
    'schwimmen', 'schwimmer', 'schwimmwettbewerb',
    'leichtathletik', 'athlet', 'leichtathletikwettbewerb',
    'olympische spiele', 'olympiad', 'olympische',
    'goldmedaille', 'silbermedaille', 'bronzemedaille',
    'marathon', 'marathonläufer',
    'formel 1', 'f1', 'f1 rennen', 'f1 fahrer',
    'rennen', 'rennauto', 'rennfahrer',
    'sport', 'sportlich', 'sportveranstaltung',
    'athlet', 'athleten',
    'wettbewerb', 'wettkampf', 'wettbewerbe',
    'stadion', 'stadien', 'arena',
    'fan', 'fans', 'fanreaktion',
  ],
  Ekonomi: [
    // Türkçe - Piyasa, Finans, Ticaret, Bankacılık
    'borsa', 'dolar', 'euro', 'sterlin', 'yen', 'pound', 
    'faiz', 'faiz oranı', 'enflasyon', 'deflasyon', 'hiperenflasyon',
    'ekonomi', 'ekonomik', 'ekonomist', 'ekonomik durum',
    'bütçe', 'bütçe kaneşi', 'mali yıl',
    'ticaret', 'ticari', 'ticaretim', 'ticari anlaşma',
    'bitcoin', 'kripto', 'kripto para', 'altcoin', 'blockchain',
    'piyasa', 'borsa piyasası', 'pazar', 'pazarlık',
    'hisse', 'hisse senedi', 'hisse fiyatı', 'hisse değeri',
    'yatırım', 'yatırımcı', 'yatırımlar', 'yatırım fonu', 'yatırım stratejisi',
    'ihracat', 'ithalat', 'ihracat pazarı', 'ithalatçı',
    'dış ticaret', 'dış ticaret müsteşarlığı',
    'kur', 'döviz kuru', 'kur alışı', 'kur dalgalanması', 'kur farkı',
    'merkez bankası', 'tcmb', 'federal reserve', 'cb',
    'vergi', 'kdv', 'öğretmen vergisi', 'kurumlar vergisi', 'gelir vergisi',
    'kredi', 'kredi notu', 'kredi kartı', 'kredi faizi', 'krediye',
    'banka', 'bankacılık', 'banka tarafından',
    'resesyon', 'ekonomik kriz', 'kriz yönetim',
    'büyüme', 'ekonomik büyüme', 'gsyh', 'gdp',
    'şirket', 'şirke karlılığı', 'kâr', 'kâr dağıtımı',
    'fiyat', 'fiyatlandırması', 'fiyat artışı', 'fiyat düşüşü',
    'tanıtım', 'reklam', 'pazarlama', 'marka',
    // Türkçe - ÇEvre, Enerji, Kaynaklar ve Doğal Afetler
    'enerji', 'enerji kaynağı', 'enerji krizi', 'enerji politikası',
    'elektrik', 'elektriklik', 'elektrik üretimi', 'elektrique fiyatı',
    'petrol', 'petrolle', 'petrol fiyatı', 'petrol rafinerisi', 'petrol ürünleri',
    'doğalgaz', 'gaz', 'gazı', 'gaz sahası', 'gaz fiyatı',
    'kömür', 'kömürlü', 'kömür madenı',
    'çevre', 'çevresel', 'çevre koruma', 'çevre kirliliği', 'çevre değişimleri',
    'iklim', 'iklim değişikliği', 'iklim krizine', 'küresel ısınma', 'sera gazları',
    'karbon', 'karbon ayak izi', 'karbon emiişyon', 'karbon nötr',
    'atık', 'atık yönetimi', 'atık işletim', 'atık tasvifi', 'atık üreti',
    'sıfır atık', 'sıfır atık haftası', 'sıfır atık günü', 'sıfır atık projesi',
    'geri dönüşüm', 'geri dönüşümü', 'geri dönüştürüleni', 'geri dönüştürme',
    'yenilemeyi', 'yenilenebilir', 'yenilenebilir enerji', 'güneş enerjisi',
    'rüzgar enerjisi', 'hibrit teknoloji',
    'yeşil', 'yeşillik', 'yeşil alan', 'yeşil alan',
    'orman', 'ormanalık', 'ormanalık alan', 'ağaçlandırma',
    'su', 'su tasarrufu', 'su yönetimi', 'su kirlilik', 'su fiyatı', 'tatlı su',
    'bisiklet', 'bisiklet alanı', 'bisiklet yolları',
    'sosyal sorumluluk', 'kurumsal sosyal sorumluluk', 'ksr',
    'sürdürülebilirlik', 'sürdürülebilir', 'sürdürülebilir kalkınma',
    // Türkçe - İnşaat, Gayrimenkul, Emlak
    'gayrimenkul', 'gayrimenkul değeri', 'ev fiyatı',
    'emlak', 'emlakçı', 'emlak sektörü', 'emlak piyasası',
    'inşaat', 'inşaat tekinoloji', 'inşaat sektörü', 'builders',
    'veya kampanyası',
    // İngilizce - Finans, Ticaret, Ekonomi
    'market', 'stock market', 'financial market',
    'inflation', 'deflaation', 'hyperinflation',
    'economy', 'economic', 'economist', 'economic conditions',
    'budget', 'fiscal policy', 'fiscal year',
    'trade', 'commerce', 'commercial', 'trading', 'trade agreement',
    'dollar', 'currency', 'foreign exchange', 'forex',
    'crypto', 'cryptocurrency', 'bitcoin', 'ethereum',
    'investment', 'investor', 'investment portfolio', 'investment strategy',
    'export', 'import', 'exporter', 'importer',
    'interest rate', 'interest', 'interest payment',
    'stock', 'stock price', 'stock market index',
    'bank', 'banking', 'central bank', 'federal reserve',
    'credit', 'credit card', 'credit rating', 'credit score',
    'tax', 'taxation', 'income tax', 'corporate tax', 'vat',
    'recession', 'economic crisis', 'financial crisis',
    'growth', 'economic growth', 'gdp', 'gross domestic product',
    'company', 'corporate', 'profit', 'revenue',
    'price', 'pricing', 'price increase', 'price decrease',
    // İngilizce - Çevre, Enerji, Kaynaklar, Doğal Afetler
    'energy', 'energy crisis', 'energy policy', 'energy source',
    'electricity', 'power', 'power generation', 'power supply', 'power price',
    'oil', 'petroleum', 'oil price', 'oil refinery', 'crude oil',
    'gas', 'natural gas', 'gas prices', 'gas supply', 'gas station',
    'coal', 'coal mining', 'coal energy',
    'environment', 'environmental', 'environmental protection', 'pollution',
    'climate', 'climate change', 'global warming', 'greenhouse gas',
    'carbon', 'carbon footprint', 'carbon emission', 'carbon neutral',
    'waste', 'waste management', 'waste disposal', 'waste reduction',
    'zero waste', 'zero waste day', 'zero waste project',
    'recycling', 'recycle', 'recyclable', 'recycled material',
    'renewable', 'renewable energy', 'solar energy', 'wind energy',
    'green', 'greenery', 'green area', 'green space',
    'forest', 'forestation', 'reforestation', 'deforestation',
    'water', 'water conservation', 'water management', 'water pollution',
    'sustainability', 'sustainable', 'sustainable development',
    'earthquake', 'disaster', 'flood', 'emergency', 'crisis', 'evacuation',
    'natural disaster', 'weather event', 'storm',
    // İngilizce - Real Estate
    'real estate', 'property', 'housing', 'construction', 'building',
    'construction company', 'contractor', 'development project',
    // Almanca - Finans, Ticaret
    'wirtschaft', 'wirtschaftlich', 'ökonom',
    'börse', 'finanzmarkt', 'aktienmarkt',
    'haushalt', 'haushaltspolitik', 'haushaltsjahr',
    'handel', 'handelspolitik', 'handel',
    'bank', 'banken', 'zentralbank', 'bundesbank',
    'unternehmen', 'unternehmensgruppe', 'unternehmensgewinne',
    'steuer', 'steuerpolitik', 'einkommensteuer',
    'krise', 'finanz_krise', 'wirtschaftskrise',
    'konjunktur', 'konjunkturpolitik', 'konjunkturzyklus',
    // Almanca - Umwelt, Energie, Ressourcen, Naturkatastrophen (SEHR WICHTIG!)
    'umwelt', 'umweltschutz', 'umweltfreundlich', 'umweltverschmutzung',
    'energie', 'energieversorgung', 'energiequelle', 'energiepolitik',
    'strom', 'stromversorgung', 'strompreis', 'stromerzeugung',
    'öl', 'erdöl', 'ölpreise', 'ölraffinerie', 'rohöl',
    'gas', 'erdgas', 'gasversorgung', 'gaspreis', 'gastankstelle',
    'kohle', 'kohlebergbau', 'kohleenergie',
    'klima', 'klimakrise', 'klimawandel', 'globale erwärmung', 'treibhausgase',
    'kohlenstoff', 'kohlenstoff-fußabdruck', 'kohlenstoffemission',
    'abfall', 'abfallwirtschaft', 'abfallbehandlung', 'abfallverringerung',
    'nullabfall', 'null-abfall-tag', 'nullabfall-projekt',
    'recycling', 'recyceln', 'recycelbar', 'recycelmaterial',
    'erneuerbar', 'erneuerbare energie', 'solarenergie', 'windenergie',
    'grün', 'grünfläche', 'grüner raum',
    'wald', 'aufforstung', 'wiederaufforstung', 'entwaldung',
    'wasser', 'wasserschutz', 'wassermanagement', 'wasserverschmutzung',
    'nachhaltigkeit', 'nachhaltig', 'nachhaltige entwicklung',
    'erdbeben', 'desaster', 'flutkatastrophe', 'notfall', 'krise', 'evakuierung',
    'naturkatastrophe', 'wetterereignis', 'sturm',
    // Almanca - Real Estate
    'immobilien', 'grundbesitz', 'wohnungsbau', 'bauunternehmen',
    'bauunternehmer', 'bauprojekt',
  ],
  Saglik: [
    // Türkçe - Genel Sağlık Hizmetleri
    'sağlık', 'sağlık bakımı', 'sağlık işçileri', 'sağlık sistemi', 'sağlık hizmeti',
    'doktor', 'doktorlar', 'doktoru',
    'hemşire', 'hemşireler', 'hemşirelik',
    'cerrah', 'cerrahlar', 'cerrahı',
    'hastane', 'hastaneler', 'hastane yönetimi',
    'klinik', 'klinikler', 'özel klinik',
    'tıbbi', 'tıbbi hizmet', 'tıbi branş',
    'tıp fakültesi', 'tıp öğrenci',
    'eczane', 'eczacı', 'eczacılık',
    'ilaç', 'ilaçlar', 'ilaç fiyatı', 'ilaç şirketi',
    'reçete', 'reçeteli', 'reçeteli ilaç',
    'tedavi', 'tedavisi', 'tedavi yöntemi', 'tedavi protokol',
    'ameliyat', 'ameliyata', 'ameliyat öncesi', 'ameliyat sonrası',
    'anestezi', 'anestezi teknisyeni',
    'post operatif', 'pre operatif',
    'hastası', 'hastalık', 'hastalığı', 'hasta yakını',
    'hasta hikayesi', 'hasta başında',
    // Türkçe - Bulaşıcı Hastalıklar
    'koronavirus', 'covid', 'covid-19', 'covid hasta',
    'pandemi', 'pandeminin', 'pandemisi',
    'aşı', 'aşılama', 'aşılı', 'aşı bölgesi', 'aşı merkezi',
    'grip', 'gripten', 'grip aşısı', 'mevsimsel grip',
    'influenza', 'influenzaya',
    'verem', 'tüberküloz', 'tb',
    // Türkçe - Kronik Hastalıklar
    'kanser', 'kanser hastası', 'kanser tedavisi', 'kanser türleri',
    'diyabet', 'diyabetli', 'diyabet hastası', 'şeker hastalığı',
    'hipertansiyon', 'yüksek tansiyon', 'tansiyon hastası',
    'kalp', 'kalp hastası', 'kalp hastalığı', 'kalp krizi', 'kardiyoloji',
    'stroke', 'beyin kanaması', 'felç', 'felç hastası',
    'astım', 'astımlı', 'akciğer hastalığı',
    // Türkçe - Ruh Sağlığı
    'ruh sağlığı', 'psikiyatri', 'depresyon', 'anksiyete',
    'psikolog', 'psikiyatrist',
    'mental sağlık', 'davranış terapisi',
    // Türkçe - Sağlık Genel Terimler
    'bağışıklık', 'bağışıklık sistemi', 'bağışıklık eksikliği',
    'ebe', 'ebelik', 'doğum',
    'hamilelik', 'hamile', 'hamileliğin',
    'obezite', 'obez', 'kilolu', 'kilo problemi',
    'beslenme', 'diyetetisyen',
    'fizyoterapisi', 'fizyoterapı', 'fizyoterapist',
    'terapi', 'terapisi', 'terapist',
    'vitamin', 'mineraller', 'supplement',
    'kan', 'kan türü', 'kan transfüzyon', 'kan bağışı',
    'organ nakli', 'transplant',
    // İngilizce
    'health', 'healthcare', 'health system', 'health service',
    'doctor', 'physician', 'medical doctor', 'doctors',
    'nurse', 'nurses', 'nursing',
    'surgeon', 'surgeon general', 'surgeons',
    'hospital', 'hospitals', 'hospital care',
    'clinic', 'clinics', 'clinical', 'clinical trial',
    'medical', 'medical care', 'medical student', 'medical school',
    'pharmacy', 'pharmacist', 'pharmaceutical',
    'medicine', 'medication', 'drug', 'drugs',
    'treatment', 'treatment plan', 'treatment of',
    'disease', 'diseases', 'disease control',
    'illness', 'sick', 'patient', 'patients',
    'surgery', 'surgical', 'surgical procedure',
    'anesthesia', 'anesthesiologist',
    'coronavirus', 'covid-19', 'covid', 'pandemic', 'infectious',
    'vaccine', 'vaccination', 'vaccinated', 'vaccine doses',
    'virus', 'viral', 'viral infection',
    'cancer', 'tumor', 'malignant', 'tumor removal',
    'chemotherapy', 'chemotherapy treatment', 'oncology',
    'diabetes', 'diabetic', 'blood sugar', 'blood glucose',
    'heart disease', 'cardiac', 'cardiology', 'cardiologist',
    'hypertension', 'blood pressure', 'high blood pressure',
    'stroke', 'brain hemorrhage', 'brain damage',
    'mental health', 'depression', 'anxiety', 'psychiatric',
    'immune system', 'immune response', 'immunity',
    'therapy', 'therapist', 'psychiatric therapy',
    'pregnancy', 'pregnant', 'births', 'obstetrics',
    'obesity', 'overweight', 'weight loss', 'diet',
    'nutrition', 'nutritionist', 'dietary',
    'physical therapy', 'rehabilitation', 'physical medicine',
    // Almanca
    'gesundheit', 'gesundheitswesen', 'gesundheitssystem', 'gesundheitspflege',
    'arzt', 'ärztin', 'ärzte', 'facharzt',
    'krankenschwester', 'krankenpfleger', 'krankenwaage', 'krankenpflage',
    'chirurg', 'chirurgie', 'chirurgischer eingriff',
    'krankenhaus', 'krankenhäuser', 'klinik', 'kliniken',
    'medizin', 'medizinisch', 'medizinische',
    'apotheke', 'apotheker', 'apothekerin',
    'medikament', 'arzneimittel', 'medikamente',
    'rezept', 'rezepte',
    'behandlung', 'behandlungen', 'medizinische behandlung',
    'krankheit', 'erkrankung', 'krankheitssymptome',
    'operation', 'operiert', 'operieren',
    'narkose', 'narkosearzt',
    'patient', 'patienten', 'patientenbehandlung',
    'coronavirus', 'corona', 'covid-19', 'pandemi', 'pandemie',
    'virus', 'virusinfekt', 'grippevirus',
    'grippe', 'influenza', 'erkältung', 'erkrankt',
    'impfung', 'impfstoff', 'impfen', 'geimpft',
    'krebs', 'krebs patient', 'krebszellen', 'krebsforschung',
    'therapie', 'chemotherapie', 'radiotherapie',
    'diabetes', 'diabetiker', 'blutzucker',
    'herzkrankheit', 'herzinfarkt', 'herzinsuffizienz', 'kardiologie',
    'schlaganfall', 'hirnblutung', 'hirnschlag',
    'psychische gesundheit', 'depression', 'angststörung', 'psychiatrie',
    'übergewicht', 'adipositas',  'ernährung', 'diätassistentin',
    'immunsystem', 'immunität', 'immundefekt',
    'schwangerschaft', 'schwanger', 'geburt', 'hebamme',
    'therapist', 'physiotherapie', 'physiotherapeut',
  ],
  Teknoloji: [
    // Türkçe - Genel Teknoloji
    'teknoloji', 'teknoloji sektörü', 'teknoloji şirketi', 'teknolojik',
    'dijital', 'dijitalleşme', 'dijital dönüşüm',
    'internet', 'internet hızı', 'internet sağlayıcı',
    'web', 'web sitesi', 'web uygulaması', 'web tasarımı',
    'yazılım', 'yazılım geliştirici', 'yazılım şirketi', 'yazılım hatası',
    'uygulama', 'mobil uygulama', 'uygulama mağazası',
    'bilgisayar', 'bilgisayar bilimi', 'bilgisayarcı', 'bilgisayar güvenliği',
    'siber', 'siber saldırı', 'siber güvenlik', 'siber tehdit',
    'robot', 'robotik', 'robotlar',
    'yapay zeka', 'ai', 'machine learning',
    'veri', 'veri analizi', 'veri güvenliği', 'veri tabanı',
    'cihaz', 'akıllı cihaz', 'ioT',
    'sistem', 'sistem güvenliği', 'sistem oyunuzda',
    // Türkçe - Mobil Platformlar ve Cihazlar
    'iphone', 'iphone modeli', 'apple iphone',
    'android', 'android telefonu', 'android sistem',
    'smartphone', 'akıllı telefon',
    'tablet', 'ipad',
    // Türkçe - Bilgisayar Donanımı
    'chip', 'gpu', 'cpu', 'işlemci',
    'ram', 'hafıza', 'depolama',
    'grafik kartı', 'görüntü kartı',
    'batarya', 'pil',
    // Türkçe - Ağ ve İletişim
    '5g', '4g', 'wifi', 'bluetooth', 'ağ',
    'iletişim', 'haberleşme', 'telekomünikasyon',
    // Türkçe - İşletim Sistemleri
    'windows', 'linux', 'macos', 'os',
    // Türkçe - Uygulamalar ve Yazılımlar
    'chatgpt', 'gpt', 'copilot',
    'python', 'java', 'javascript', 'typescript', 'code',
    'github', 'git', 'entegrasyonu',
    // Türkçe - İnternet Şirketleri
    'microsoft', 'google', 'apple', 'amazon', 'meta', 'facebook',
    'tesla', 'spacex', 'elon musk',
    'nvidia', 'amd', 'intel',
    // Türkçe - İnovasyon ve Başlangıçlar
    'startup', 'girişim', 'girişimci',
    'inovasyon', 'yenilikçi',
    'ürün lansman', 'ürün duyurusu',
    // Türkçe - Blokzincir ve Kripto
    'blockchain', 'blokzincir',
    'kripto', 'kripto para', 'bitcoin', 'ethereum',
    'nft', 'web3',
    // Türkçe - Yapay Zeka
    'derin öğrenme', 'sinir ağı', 'algoritma',
    'model', 'eğitim', 'veri seti',
    // Türkçe - Uzay Teknolojisi
    'uzay', 'uzay teknolojisi', 'uzay aracı',
    'nasa', 'spacex', 'roket', 'uydu',
    // Türkçe - Otonom Araçlar VE Elektrikli Araçlar (SADECE TEKNOLOJI ODAKLI)
    'elektrikli araç', 'elektrik arabası', 'elektrik otomobili',
    'otonom araç', 'otonom otomobil', 'sürücüsüz araç', 'sürücüsüz otomobil',
    'otonom sürüş', 'otonom teknoloji', 'otonom sistem',
    'tesla', 'ev araç', 'hibrit araç', 'hibrit otomobil',
    'batarya', 'batarya teknoloji', 'batarya kapasitesi', 'pil teknoloji', 'şarj', 'hızlı şarj',
    'dön araç kaynağı', 'motor teknoloji', 'elektrik motor', 'fuel cell',
    // Türkçe - Dron ve Hava Araçları
    'dron', 'insansız hava aracı', 'drone', 'hava dronu', 'otonom drone',
    // Türkçe - Oyun
    'oyun', 'oyuncu', 'oyun geliştirmesi', 'esport',
    'metaverse', 'sanal gerçeklik',
    // İngilizce
    'technology', 'tech', 'technological',
    'digital', 'digitalization', 'digital transformation',
    'internet', 'internet speed', 'internet service',
    'web', 'website', 'web app', 'web design',
    'software', 'software development', 'software company', 'software update',
    'app', 'mobile app', 'application',
    'computer', 'computer science', 'computing',
    'cyber', 'cyber attack', 'cybersecurity', 'cyber threat',
    'robot', 'robotics', 'automation',
    'artificial intelligence', 'ai', 'machine learning', 'deep learning',
    'data', 'data analysis', 'data security', 'database',
    'device', 'smart device', 'iot',
    'system', 'system security',
    'iphone', 'iphone model',
    'android', 'android phone',
    'smartphone', 'mobile phone',
    'tablet', 'ipad',
    'chip', 'gpu', 'cpu', 'processor',
    'memory', 'ram', 'storage',
    'graphic card', 'graphics',
    'battery', 'power',
    '5g', '4g', 'wifi', 'bluetooth', 'network',
    'communication', 'telecommunications',
    'windows', 'linux', 'macos', 'os',
    'chatgpt', 'gpt', 'copilot',
    'python', 'java', 'javascript', 'typescript', 'code', 'coding',
    'github', 'git',
    'microsoft', 'google', 'apple', 'amazon', 'meta', 'facebook',
    'tesla', 'spacex', 'elon musk',
    'nvidia', 'amd', 'intel',
    'startup', 'venture',
    'innovation', 'innovative',
    'product launch', 'product announcement',
    'blockchain', 'bitcoin', 'ethereum',
    'nft', 'web3',
    'space', 'space technology', 'spacecraft',
    'nasa', 'spacex', 'rocket', 'satellite',
    'electric vehicle', 'electric car', 'electric automobile', 'ev car',
    'autonomous vehicle', 'autonomous car', 'autonomous automobile', 'self-driving car',
    'self-driving vehicle', 'driverless car', 'driverless vehicle',
    'tesla', 'ev technology', 'hybrid vehicle', 'hybrid car',
    'battery technology', 'battery capacity', 'fast charging', 'charging station',
    'electric motor', 'fuel cell', 'fuel cell vehicle',
    'drone', 'unmanned aerial', 'autonomous drone',
    'gaming', 'gamer', 'game development', 'esports',
    'metaverse', 'virtual reality',
    'virtual', 'augmented reality',
    // Almanca
    'technologie', 'technik', 'technologisch',
    'digital', 'digitalisierung', 'digitale transformation',
    'internet', 'internetgeschwindigkeit', 'internetanbieter',
    'web', 'webseite', 'webanwendung', 'webdesign',
    'software', 'softwareentwicklung', 'softwareunternehmen',
    'anwendung', 'app', 'mobile app',
    'computer', 'informatik', 'computerbranche',
    'cyber', 'cyberangriff', 'cybersicherheit',
    'roboter', 'robotik', 'automatisierung',
    'künstliche intelligenz', 'ai', 'maschinelles lernen',
    'daten', 'datenanalyse', 'datensicherheit', 'datenbank',
    'gerät', 'smartgerät', 'iot',
    'system', 'systemsicherheit',
    'iphone', 'iphonemodell',
    'android', 'androidtelefon',
    'smartphone', 'mobiltelefon',
    'tablet', 'ipad',
    'chip', 'gpu', 'cpu', 'prozessor',
    'speicher', 'ram',
    'grafikkarte', 'grafik',
    'akku', 'batterie',
    '5g', '4g', 'wifi', 'bluetooth', 'netz',
    'kommunikation', 'telekommunikation',
    'windows', 'linux', 'macos', 'betriebssystem',
    'chatgpt', 'gpt', 'copilot',
    'python', 'java', 'javascript', 'typescript', 'code',
    'github', 'git',
    'microsoft', 'google', 'apple', 'amazon', 'meta', 'facebook',
    'tesla', 'spacex', 'elon musk',
    'nvidia', 'amd', 'intel',
    'startup', 'unternehmung',
    'innovation', 'innovativ',
    'produkteinführung', 'produktankündigung',
    'blockchain', 'bitcoin', 'ethereum',
    'nft', 'web3',
    'raum', 'raumfahrttechnologie', 'raumfahrzeug',
    'nasa', 'spacex', 'rakete', 'satellit',
    'elektrofahrzeug', 'elektroauto', 'elektromobil',
    'autonomes fahrzeug', 'autonomes auto', 'autonomes automobil',
    'selbstfahrendes fahrzeug', 'selbstfahrendes auto', 'fahrerlose auto',
    'tesla', 'ev technologie', 'hybrid fahrzeug', 'hybrid auto',
    'batterietechnologie', 'batteriekapazität', 'schnellladevorrichtung', 'ladestation',
    'elektromotor', 'brennstoffzelle', 'brennstoffzellenauto',
    'drohne', 'unbemannte luftfahrzeug', 'autonome drohne',
    'spiel', 'spieler', 'spielentwicklung', 'esports',
    'metaverse', 'virtuelle realität',
    'virtuell', 'erweiterte realität',
  ],
  Kultur: [
    // Türkçe - Sanat Genel
    'sanat', 'sanatçı', 'sanat eseri', 'sanat okulu', 'sanat yönetmeni',
    'sanat sergisi', 'sanat galerisi', 'sanat müzesi',
    'ressam', 'resim', 'boyama', 'tuval',
    'heykeltıraş', 'heykel', 'heyelkul', 'sanat',
    'müze', 'müze ziyareti', 'müzecilik', 'müze müdürü',
    'galeri', 'sanat galerisi', 'ekspozisyon',
    'çağdaş sanat', 'modern sanat', 'klasik sanat',
    // Türkçe - Film ve Sinema
    'film', 'filmi', 'filmler', 'filmcilik',
    'sinema', 'sinemada', 'sinemacı', 'sinema sektörü',
    'yönetmen', 'yönetmenlik', 'yönetmeni',
    'senarist', 'senaryo', 'senaryosu',
    'oyuncu', 'başrol', 'destekçi oyuncu', 'oyunculuk',
    'yapımcı', 'yapım', 'yapım şirketi', 'yapımcılık',
    'kameraman', 'müzik yönetmeni', 'mizansenist',
    'denetmen', 'saat', 'kütüphaneci',
    'film yönetmeni', 'film festivali', 'film gösterimi', 'film izle',
    'sinema oyuncusu', 'oyuncu oyunculuk',
    'premyer', 'fragman', 'trailer',
    'türk sineması', 'hollywood', 'avrupa sineması',
    // Türkçe - Müzik
    'müzik', 'müzisyen', 'müzik sanatçısı', 'müzik öğretmen',
    'şarkıcı', 'şarkı', 'şarkı söyleyen',
    'konser', 'konserler', 'canlı müzik', 'konser salonları',
    'müzik festivalı', 'müzik yarışması',
    'müzik endüstrisi', 'müzik şirketi', 'plak şirketi',
    'orkestra', 'senfonik', 'orkestra şefi',
    'bale', 'balerin', 'bale dansçısı', 'bale şirketi',
    'opera', 'operetta', 'opera sanatçısı', 'operacı',
    'tango', 'flamenco', 'latin müzik',
    'düet', 'solo', 'grup', 'band', 'müzik grubu',
    'caz', 'blues', 'rock', 'pop', 'klasik müzik',
    'müzik prodüktörü', 'müzik yapımcısı', 'ses teknisyeni',
    'nota', 'armonisi', 'melodi', 'ritim',
    'gitar', 'piyano', 'keman', 'ney', 'ud',
    'grammy', 'müzik ödülü', 'müzik ödül töreni',
    // Türkçe - Tiyatro ve Sahne Sanatları
    'tiyatro', 'tiyatro oyuncusu', 'oyuncu',
    'tiyatro sahnesinde', 'tiyatro tasarısı',
    'oyun', 'oyunun', 'oyunlar', 'temaşa',
    'sahne', 'sahne tasarısı', 'sahne dekorasyonu',
    'tiyatro yönetmeni', 'tiyatro şefi', 'tiyatro direktörü',
    'senarist', 'oyun yazarı', 'piyesci',
    'tiyatro oyuncusu', 'oyuncu performansı',
    'tiyatro festivali', 'tiyatro gösterisi', 'tiyatro sunumu',
    'dram', 'komedi', 'tragikomedi', 'tiyatro türü',
    'kültür merkezi', 'tiyatro binası', 'tiyatro salonu',
    'sahne tasarımcısı', 'kostüm tasarımcısı',
    'oynadı', 'rol oynadı', 'rol oyuncu',
    // Türkçe - Edebiyat ve Yazın
    'edebiyat', 'edebiyatçı', 'edebiyat öğretmeni', 'edebiyat elçiliği',
    'kitap', 'kitaplar', 'kitap okuma',
    'yazar', 'yazarı', 'yazarlar', 'yazarlık',
    'roman', 'romancı', 'romanı', 'romanları',
    'şiir', 'şair', 'şiirlerini', 'şiir yazarı',
    'öykü', 'hikaye', 'kısa hikaye',
    'belgesel', 'biyografi', 'otobiyografi',
    'yayınevi', 'yayın şirketi', 'yayınlanıyor',
    'edebiyat ödülü', 'nobel edebiyat', 'franz kafka',
    'kitap fuarı', 'kitap pazar',
    'okuma', 'okuyucu', 'kitap okuru',
    'türk edebiyatı', 'dünya edebiyatı', 'klasik edebiyat',
    // Türkçe - Ödüller ve Festivaller
    'ödül', 'ödülleri', 'ödül sahibi', 'ödül kazandı',
    'nobel', 'nobel ödülü', 'nobel sanatçısı',
    'oscar', 'oscar ödülü', 'oscar selen', 'oscar yapımcısı',
    'grammy', 'grammy ödülü', 'grammy müzisyen',
    'festival', 'festivalı', 'festivale', 'festivalleri',
    'cannes', 'cannes film festivali', 'cannes palme d\'or',
    'berlin', 'berlin film festivali', 'berlin ödülü',
    'venedik', 'venedik film festivali',
    'sundance', 'sundance festivali', 'sundance öz',
    'pantoflu', 'pitti uomo', 'new york moda haftası',
    // İngilizce - Art
    'art', 'artist', 'artistic', 'artwork',
    'painter', 'painting', 'sculpture', 'sculptor',
    'museum', 'gallery', 'exhibition', 'exhibition opening',
    'contemporary art', 'modern art', 'classical art',
    'restoration', 'conservation', 'art historian',
    'art school', 'art academy', 'art director',
    // İngilizce - Film and Cinema
    'film', 'films', 'filmmaker', 'filmaking',
    'cinema', 'cinematic', 'cinematography', 'cinematographer',
    'director', 'directorial', 'directing',
    'screenwriter', 'screenplay', 'script', 'scriptwriting',
    'actor', 'actress', 'acting', 'performance',
    'producer', 'production', 'production company',
    'drama', 'thriller', 'comedy', 'action movie',
    'movie premiere', 'film festival', 'film showing',
    'hollywood', 'bollywood', 'european cinema',
    'oscars', 'golden globe awards', 'bafta',
    'trailer', 'preview', 'movie review',
    // İngilizce - Music
    'music', 'musician', 'musical', 'musicality',
    'singer', 'song', 'singing', 'vocal',
    'concert', 'concerts', 'live performance', 'concert tour',
    'orchestra', 'symphonic', 'conductor', 'symphony',
    'ballet', 'ballerina', 'ballet dancer', 'ballet company',
    'opera', 'operetta', 'opera singer', 'soprano',
    'jazz', 'blues', 'rock', 'pop', 'classical music', 'folk music',
    'producer', 'music producer', 'sound engineer',
    'instrument', 'guitar', 'piano', 'violin',
    'grammy awards', 'music award', 'music festival',
    'album', 'single', 'hit song', 'chart topping',
    // İngilizce - Theater
    'theater', 'theatre', 'theatrical', 'stage',
    'actor', 'actress', 'performance', 'acting',
    'play', 'drama', 'comedy', 'tragedy',
    'playwright', 'scriptwriter', 'drama writer',
    'stage designer', 'costume designer', 'lighting designer',
    'theater festival', 'theater production', 'theater premiere',
    'broadway', 'west end', 'theater company',
    'rehearsal', 'performance', 'opening night',
    // İngilizce - Literature
    'literature', 'literary', 'literature scholar',
    'author', 'writer', 'novelist', 'poet', 'poetry',
    'book', 'novel', 'short story', 'tale',
    'biography', 'autobiography', 'memoir',
    'publishing', 'publisher', 'published',
    'literary award', 'noble prize', 'nobel literature',
    'book fair', 'book festival', 'book launch',
    'reader', 'reading', 'book review',
    'fiction', 'non-fiction', 'classic literature',
    // Almanca
    'kunst', 'künstler', 'künstlerisch', 'kunstwerk',
    'maler', 'malerei', 'skulptur', 'bildhauer',
    'museum', 'galerie', 'ausstellung', 'ausstellungseröffnung',
    'gegenwartskunst', 'moderne kunst', 'klassische kunst',
    'restoration', 'kunsthistoriker',
    'kunstschule', 'kunstakademie', 'kunstdirektor',
    // Almanca - Film
    'film', 'filme', 'filmemacher', 'filmherstellung',
    'kino', 'kinematisch', 'kinematografie', 'kameramann',
    'regisseur', 'regie', 'regieführung',
    'drehbuchautor', 'drehbuch', 'skript', 'skriptentwicklung',
    'schauspieler', 'schauspielerin', 'schauspielkunst', 'auftritt',
    'produzent', 'produktion', 'produktionsgesellschaft',
    'drama', 'thriller', 'komödie', 'actionfilm',
    'filmpremiere', 'filmfestival', 'filmvorführung',
    'hollywood', 'bollywood', 'europäisches kino',
    'oscars', 'golden globe awards', 'bafta',
    'trailer', 'vorschau', 'filmkritik',
    // Almanca - Musik
    'musik', 'musiker', 'musikal', 'musikalität',
    'sänger', 'lied', 'gesang', 'vokalist',
    'konzert', 'konzerte', 'liveperformance', 'konzerttournee',
    'orchester', 'sinfonisch', 'kapellmeister', 'symphonie',
    'ballett', 'ballerino', 'ballettänzer', 'ballettcompanie',
    'oper', 'operette', 'opernsänger', 'sopran',
    'jazz', 'blues', 'rock', 'pop', 'klassische musik', 'volksmusik',
    'produzent', 'musikproduzent', 'toningenieur',
    'musikinstrument', 'gitarre', 'klavier', 'violine',
    'grammy awards', 'musikpreis', 'musikfestival',
    'album', 'single', 'hit lied', 'charttopping',
    // Almanca - Theater
    'theater', 'theatralisch', 'bühn',
    'schauspieler', 'schauspielerin', 'auftritt', 'schauspielkunst',
    'theaterstück', 'drama', 'komödie', 'tragödie',
    'dramatiker', 'drehbuchautor', 'dramenschreiber',
    'bühnenbild', 'kostümassistenten', 'lichtdesigner',
    'theaterfestival', 'theaterproduktion', 'theaterpremiere',
    'broadway', 'west end', 'theatergesellschaft',
    'proben', 'auftritt', 'premiere',
    // Almanca - Literatur
    'literatur', 'literarisch', 'literaturwissenschaftler',
    'autor', 'schriftsteller', 'romanschriftsteller', 'dichter', 'poesie',
    'buch', 'roman', 'kurzgeschichte', 'erzählung',
    'biografie', 'autobiografie', 'memoiren',
    'verlag', 'verleger', 'veröffentlicht',
    'literaturpreis', 'nobelpreis', 'nobelpreis literatur',
    'buchmesse', 'buchfestival', 'buchstart',
    'leser', 'lesen', 'buchbesprechung',
    'fiktion', 'sachbuch', 'klassische literatur',
  ],
  Magazin: [
    // Türkçe - Ünlüler ve Şöhretler (SİYASİ LIDERLER DEĞİL!)
    'ünlü', 'ünlüleri', 'ünlü kişi', 'ünlü oyuncu',
    'yıldız', 'yıldızlar', 'süperstar',
    'aktör', 'aktörleri', 'oyuncu', 'oyunculuk',
    'aktris', 'kadın oyuncu', 'oyuncu kadın',
    'senarist', 'senaristlik',
    'yönetmen', 'yönetmenlik', 'film yönetmeni', 'yönetmen yapıtları',
    'model', 'modeller', 'manken', 'defileleri',
    'youtuber', 'tiktoker', 'instagramcı', 'influencer', 'sosyal medya yıldızı',
    'web seri yıldız', 'content creator',
    'sporcu ünlü', 'sporcu eşi', 'ünlü sporcu', 'futbolcu eşi',
    'müzisyen', 'müzik yıldızı', 'şarkıcı', 'şarkıcıları',
    'konservatuar', 'konservatuvar öğrenc',
    // Türkçe - İlişkiler, Evlilik, Duygusal Hayat
    'boşandı', 'boşanmalar', 'boşanma haberler', 'boşanma davas',
    'boşanma süreci', 'boşanma kararı', 'boşan oyuncu', 'boşan meşhur',
    'ayrılık', 'ayrılığı', 'ayrılanlar', 'ünlü ayrılık',
    'ayrılmış oyuncu', 'ayrılmış eşler',
    'evlilik', 'evlilikleri', 'evlilik muhabbet', 'evlilik haberi',
    'evlilik öyküsü', 'evlilik meselesi',
    'nikah', 'nikahlandı', 'nikah günü', 'nikah merasimi',
    'düğün', 'düğünü', 'düğünün', 'düğün haberi', 'düğün planlaması',
    'düğün fotoğraf', 'düğün yeri', 'evlenme düğünü',
    'gelin', 'gelin kıyafet', 'gelin kuaför',
    'damat', 'damat giysisi',
    'aşk', 'aşkı', 'aşk öyküsü', 'aşk ünlü', 'aşk haberler',
    'aşkın başlaması', 'aşk bitimi', 'aşk seçimi',
    'ilişki', 'ilişkiler', 'ilişkisi', 'ilişkinin', 'ilişkisini', 'ilişkileri',
    'romantik ilişki', 'yeni ilişki', 'çift ilişkisi',
    'çift', 'çiftler', 'çiftlerin', 'ünlü çiftler', 'çift haberleri',
    'çift ayrıldı', 'çift evlendi', 'çift birlikt',
    'romantik', 'romantizm', 'romantic gest',
    'eski partner', 'eski sevgili', 'eski eş', 'eski partner şimdi',
    'yeni sevgili', 'yeni partnerler', 'yeni öpüşm',
    'ruh eşi', 'eş', 'eşi', 'eşinin', 'eşine', 'eşle',
    'kocası', 'eşi', 'karısı',
    'sevgili', 'sevgilisi', 'sevgililerinin',
    'flört', 'flörtleş', 'flörtü',
    'paparazzi', 'paparazzi fotoğrafı', 'paparazzi haberler',
    'romantik kız havası', 'romantic gest', 'romantik andı',
    // Türkçe - Güzellik, Estetik, Şıklık
    'güzellik', 'güzel kadın', 'güzel aktris', 'güzel model',
    'güzellik yarışması', 'güzellik kraliçes', 'güzellik tayı',
    'estetik', 'estetik ameliyatı', 'estetik cerrah', 'estetik hizmetler',
    'plastik cerrahi', 'plastik cerrah', 'cerrahi müdahale',
    'ameliyat', 'ameliyatı', 'ameliyat sonrası', 'ameliyat öncesi',
    'botoks', 'botox enjeksiyon', 'botox', 'botoxlu',
    'dolgu', 'dolgu yapıldı', 'yüz doldurma',
    'liposuction', 'liposuktion ameliyatı',
    'implant', 'göğüs implant', 'implant ameliyatı',
    'yüz germe', 'yüz germe ameliyatı', 'yüz estetiği',
    'burun estetiği', 'burun ameliyatı', 'burun şekli',
    'piliç serileri', 'cilt tedavisi', 'cilt ürünleri',
    'cilt tonu', 'cilt yönetimi', 'cilt bakım',
    'kilo verme', 'kilo kaybı', 'kilo düşüşü', 'kilo verdi',
    'vücut değişim', 'vücut dönüşüm',
    'fit vücut', 'fitnes hedefleri', 'fitnes şampiyonu',
    'diyete', 'diyetler', 'diyeti', 'diyetli',
    'fitnes', 'fitnes programı', 'fitnes antrenmanı', 'fitnes hedefleri',
    'yoga', 'yoga egzersiz', 'yoga kurs',
    'pilates', 'pilates sınıf',
    'gym', 'gym antrenmanı', 'gym hocası',
    'vücut geliştirme', 'vücut şekli', 'kasları',
    'sağlıklı yaşam', 'sağlıklı beslenme', 'sağlık İyileştir',
    // Türkçe - Moda, Stil, Tarz
    'moda', 'moda tasarımcısı', 'moda sektörü', 'moda haftası', 'moda şov',
    'stil', 'kişisel stil', 'stil danışmanı', 'stil trendleri',
    'kıyafet', 'kıyafet seçimi', 'kıyafet kombinasyonu', 'kıyafet markası',
    'elbise', 'elbise tasarımları', 'elbise modası', 'elbiseyle',
    'ayakkabı', 'ayakkabı koleksiyonu', 'ayakkabı tasarımı', 'ayakkabı markası',
    'aksesuar', 'aksesuar seçimi', 'tasarımcı aksesuarlar',
    'çanta', 'designer çanta', 'tasarımcı çantası', 'çanta koleksiyonu',
    'takı', 'mücevher', 'elmas takı', 'altın takı',
    'saat', 'tasarımcı saat', 'kol saati', 'saat markası',
    'saç', 'saç kesimi', 'saç rengeri', 'saç şekillendirm',
    'kuaför', 'kuaför trendleri', 'kuaför stillleri',
    'makyaj', 'makyaj ürünleri', 'makyaj danışmanı', 'makyaj sanatçısı',
    'cosmetik', 'kozmetik ürünleri', 'kaş tırnak',
    'designer', 'tasarımcı elbise', 'tasarımcı brand', 'tasarımcı ayakkabı',
    'defile', 'podyum', 'catwalk', 'moda gösterisi',
    'moda haftası', 'paris moda', 'milan fashion week',
    'haute couture', 'pret-a-porter', 'ready wear',
    'renk', 'renk kombinasyonu', 'renk matching',
    'aksesuar şıklaştır', 'şık giyinş', 'şık stil',
    'krendileri takip et', 'trend colors', 'trend stilleri',
    // Türkçe - Aile, Çocuk, Bebek
    'aile', 'ailesi', 'aileyle', 'aile haberleri', 'aile yaşamı',
    'çocuk', 'çocuğu', 'çocuğun', 'çocuğunun', 'çocuklar', 'çocuklarının',
    'çocuk haberleri', 'çocuk fotoğraf', 'çocuk yaşamı',
    'bebek', 'bebeği', 'bebeğin', 'bebek haberleri', 'yeni günleri',
    'newborn', 'bebek fotoğrafı', 'bebek kalıntı', 'bebeğin fotoğrafları',
    'hamilelik', 'hamile', 'hamileliğin', 'hamileliğin son günleri',
    'hamile fotoğraf', 'hamile stile', 'hamile yaşamı', 'pregnant photoshoot',
    'doğum', 'doğuma', 'doğum günü', 'doğum haberi', 'doğum sevinci',
    'bebek adlandırma', 'bebeğe ad verme', 'isim seçim',
    'ebeveyn', 'ebeveynlik', 'anne', 'annesi', 'anne-baba',
    'baba', 'babası', 'baba rolü',
    'kardeş', 'kardeşi', 'kardeşleri', 'kardeş ilişkisi',
    'aile durumu', 'aile yapısı', 'aile bağları', 'aile dinamiği',
    'ebeveyn-çocuk', 'çocuk eğitim', 'çocuk bakımı',
    // Türkçe - Yaşam Tarzı ve Sosyal Medya
    'yaşamtarzı', 'yaşam stilı', 'yaşam biçimi', 'yaşamını',
    'yaşam fotoğraf', 'yaşam detayları', 'günlük yaşam',
    'sosyal medya', 'sosyal medya paylaşımı', 'sosyal medya yıldız',
    'instagram', 'instagram fenomeni', 'instagram hesapı', 'instagramda',
    'instagramda takip', 'instagramdan paylaş',
    'tiktok', 'tiktok videosu', 'tiktok yıldız', 'tiktokta',
    'tiktoktaki videol', 'tiktok fenömeni',
    'facebook', 'facebook paylaş', 'facebook haberi',
    'twitter', 'twitter haberi', 'tweet',
    'snapchat', 'snapchat hesapı',
    'viral', 'viral video', 'viral trend', 'virali',
    'trending', 'trending topic', 'trending çekim',
    'hashtag', 'hashtag trendi', 'hashtag kullan',
    'paylaş', 'paylaşımı', 'selfie', 'selfie fotoğrafı',
    'fotoğraf', 'fotoğraflı paylaşım', 'fotoğraf galerisi', 'fotoğraf seçim',
    'video', 'video paylaşımı', 'video çekişi',
    'takipçi', 'takipçiler', 'takipçi sayısı', 'takipçi artışı',
    'beğeni', 'beğeniler', 'yorum', 'yorumlar',
    'engagement', 'interaksi', 'etkileşim', 'sosyal etkileş',
    // İngilizce
    'celebrity', 'celebrities', 'celebrity news', 'celebrity gossip',
    'famous', 'famous person', 'famous actress', 'famous actor',
    'star', 'stars', 'movie star', 'tv star', 'celebrity stars',
    'actor', 'actress', 'actors', 'actresses',
    'model', 'fashion model', 'models', 'supermodel',
    'influencer', 'influencers', 'social media influencer',
    'youtuber', 'content creator', 'social media creator',
    'musician', 'pop star', 'music star', 'singer',
    'celebrity couple', 'power couple', 'hollywood couple',
    'divorced', 'divorce', 'divorce news', 'celebrity breakup', 'breakups',
    'marriage', 'married', 'marriage news', 'celebrity wedding',
    'wedding', 'bride', 'groom', 'wedding dress', 'wedding venue',
    'couple', 'couples', 'celebrity couples', 'newlyweds',
    'romance', 'romantic', 'romance news', 'romantic date',
    'love', 'love story', 'love life', 'love triangle',
    'dating', 'dating news', 'who is dating',
    'relationship', 'relationships', 'celebrity relationship', 'relationship news',
    'breakup', 'split', 'broken up', 'ended relationship',
    'ex', 'ex-girlfriend', 'ex-boyfriend', 'ex-spouse',
    'beauty', 'beautif', 'beautiful woman', 'gorgeous',
    'handsome', 'attractive', 'stunning',
    'cosmetic surgery', 'plastic surgery', 'surgery procedure',
    'botox', 'filler', 'augmentation', 'implant',
    'facelift', 'tummy tuck', 'breast surgery',
    'fitness', 'gym', 'workout', 'workout routine', 'fitness journey',
    'weight loss', 'lost weight', 'weight gain', 'diet',
    'healthy', 'wellness', 'health journey', 'diet plan',
    'yoga', 'pilates', 'exercise routine',
    'fashion', 'style', 'fashion trend', 'style inspiration',
    'outfit', 'looks', 'dressed', 'outfit of the day',
    'dress', 'gown', 'couture',
    'designer', 'designer label', 'designer clothes', 'designer brand',
    'luxury', 'luxury brand', 'high fashion',
    'makeup', 'makeup look', 'makeup artist', 'makeup tutorial',
    'hair', 'hairstyle', 'haircut', 'new hair',
    'accessories', 'jewelry', 'jewels', 'handbag', 'shoes',
    'lifestyle', 'lifestyle blog', 'lifestyle content',
    'instagram', 'instagram post', 'instagram story', 'instagram account',
    'tiktok', 'tiktok video', 'tiktok star', 'tiktok challenge',
    'viral', 'viral video', 'viral trend', 'viral moment',
    'trending', 'trending topic', 'trending now',
    'family', 'family life', 'family photo', 'family news',
    'baby', 'babies', 'newborn', 'pregnancy', 'pregnant',
    'children', 'kids', 'parenting', 'parenting tips',
    'motherhood', 'fatherhood', 'parent life',
    'social media', 'social media star', 'social media presence',
    'fame', 'celebrity', 'celebrity status', 'becoming famous',
    'paparazzi', 'paparazzi photos', 'paparazzi moment',
    'photoshoot', 'photo', 'photos', 'picture', 'pictures',
    'selfie', 'selfies',
    'followers', 'following', 'fan', 'fans', 'fan culture',
    'gossip', 'celebrity gossip', 'gossip news',
    // Almanca
    'promi', 'promis', 'berühmtheit', 'promiträsche', 'prominente',
    'celebrity', 'celebrities', 'promi news', 'promi-klatsch',
    'schauspieler', 'schauspielerin', 'schauspielerinnen', 'schauspielerin',
    'star', 'stars', 'starlett', 'filmstar', 'tvstar',
    'model', 'supermodel', 'modemodell', 'catwalk-modell',
    'influencer', 'influencer', 'social media influencer',
    'youtuber', 'content creator', 'streaming-star',
    'musikstar', 'musikerin', 'popsänger', 'sänger',
    'promi-paar', 'prominentenpaare', 'berühmtheit paar',
    'scheidung', 'ehescheidung', 'scheiden', 'geschieden',
    'trennung', 'trennung news', 'prominententrennungen',
    'hochzeit', 'eheschließung', 'trauung', 'vermählung',
    'braut', 'bräutigam', 'hochzeitskleider', 'hochzeitsvenue',
    'beziehung', 'beziehungen', 'promi beziehung', 'beziehungsnews',
    'liebe', 'liebesgeschichte', 'liebesleben', 'liebesdreieck',
    'dating', 'datingnews', 'datinggerücht',
    'romance', 'romantik', 'romantisches datum',
    'schönheit', 'schöne frau', 'schöner mann', 'attraktiv',
    'gorgeous', 'wunderschön', 'atemberaubend',
    'cosmetische chirurgie', 'plastische chirurgie', 'chirurgischer eingriff',
    'botox', 'filler', 'vergrößerung', 'implantat',
    'gesichtslifting', 'bauchstraffung', 'brustchirurgie',
    'fitness', 'fitnessstudio', 'trainingsroutine', 'fitnessgereät',
    'gewichtsverlust', 'gewicht verlieren', 'gewichtszunahme', 'diät',
    'gesund', 'wellness', 'gesundheitsnews', 'diätplan',
    'yoga', 'pilates', 'trainingsroutine',
    'mode', 'stil', 'modetrend', 'stilinspiration',
    'outfit', 'looks', 'gekleidet', 'outfit des tages',
    'kleid', 'abendkleid', 'couture',
    'designer', 'designerlabel', 'designerkleidung', 'designermarke',
    'luxus', 'luxusmarke', 'hochmode',
    'makeup', 'makeup-look', 'makeup-künstler', 'makeup-anleitung',
    'haar', 'frisur', 'haarschnitt', 'neue frisur',
    'accessoires', 'schmuck', 'juwelen', 'handtasche', 'schuhe',
    'lebensstil', 'lifestyle-blog', 'lifestyle-inhalt',
    'instagram', 'instagram-post', 'instagram-story', 'instagram-konto',
    'tiktok', 'tiktok-video', 'tiktok-star', 'tiktok-herausforderung',
    'virale', 'virales video', 'viraler trend', 'viraler moment',
    'trending', 'trending-thema', 'trending-now',
    'Familie', 'Familienlében', 'Familienfoto', 'Familiënews',
    'baby', 'babys', 'neugeborenes', 'schwangerschaft', 'schwanger',
    'kinder', 'kids', 'elternschaft', 'elternschaftstipps',
    'mutterschaft', 'vaterschaft', 'elternleben',
    'social media', 'social-media-star', 'social-media-anwesenheit',
    'ruhm', 'prominenz', 'promi-status', 'berühmtheit',
    'paparazzi', 'paparazzi-fotos', 'paparazzi-moment',
    'fotoshooting', 'foto', 'fotos', 'bild', 'bilder',
    'selfie', 'selfies',
    'follower', 'following', 'fan', 'fans', 'fankultur',
    'klatsch', 'promi-klatsch', 'klatsch-news',
  ],
  Siyaset: [
    // Türkçe - Birinci Dereceden Siyasi Aktörler (LİDERLER)
    'erdoğan', 'recep tayyip erdoğan', 'başkan erdoğan',
    'kılıçdaroğlu', 'kemal kılıçdaroğlu', 'kılıçdar oğlu',
    'akşener', 'meral akşener',
    'bahçeli', 'devlet bahçeli',
    'babacan', 'ali babacan',
    'demirtaş', 'selahattin demirtaş',
    'davutoğlu', 'ahmet davutoğlu',
    'gül', 'abdullah gül',
    'demirel', 'süleyman demirel',
    'özdemir', 'özgür öz',
    // Türkçe - Siyasi Makamlar (HUKUK/SUÇ DEĞİL!)
    'cumhubaşkanı', 'cumhubaşkanlığı', 'cumhubaşkanlık',
    'başbakan', 'başbakanı', 'başbakanlık',
    'milletvekili', 'vekil',
    'meclis üyesi', 'mecliste',
    'belediye başkanı', 'belediye başkanlığı',
    'büyükelçi', 'büyükelçilik',
    'konsolos', 'konsoloslu',
    'vali', 'valilik',
    'kaymakam', 'kaymakamlar',
    'muhtar', 'muhtarlar',
    'bakan', 'bakanlık', 'bakanlığı', 'bakanlar',
    'hükümet', 'hükümetin', 'hükümet konaği',
    'İçişleri Bakanlığı', 'işçi bakanlığı', 'dışişleri bakanlığı',
    'meclis', 'tbmm', 'türkiye büyük millet meclisi',
    'belediye', 'belediye meclisi', 'belediye yönetnetkli',
    // Türkçe - Siyasi Partiler ve Ideolojiler
    'ak parti', 'akp',
    'chp', 'cumhuriyet halk partisi',
    'mhp', 'milliyetçi hareket partisi',
    'iyi parti',
    'hdp', 'halkların demokartik partisi',
    'dem parti',
    'sp', 'saadet partisi',
    'dask',
    'dsp', 'devlet bahçeli sosyaldemokrat',
    // Türkçe Seçim Konuları
    'seçim', 'seçim yasakları', 'seçim tarihi',
    'genel seçim', 'yerel seçim',
    'cumhurbaşkanlık seçimi', 'cumhurbaşkanlık seçimleri',
    'referandum', 'halk oylaması',
    'oy', 'oy sanığı', 'oy verme',
    'kampanya', 'siyasi kampanya',
    'seçmene', 'seçmen', 'seçmenleri',
    'sandık', 'seçim sandığı',
    // Türkçe Siyasi Harita/Diplomasi
    'dışişleri', 'türkiye dışişleri',
    'tahran', 'viyana', 'washington',
    'barış', 'barış süreci',
    'anlaşma', 'anlaşması',
    'muhalefet', 'muhaliefet', 'muhalifleri',
    'koalişyon', 'koalisyonu',
    'kabiine', 'kabine değişikliği',
    // İngilizce - Uluslararası Liderler
    'trump', 'donald trump',
    'biden', 'joe biden',
    'putin', 'vladimir putin',
    'zelensky', 'volodymyr zelensky',
    'macron', 'emmanuel macron',
    'scholz', 'olaf scholz',
    'merkel', 'angela merkel',
    'sunak', 'rishi sunak',
    'cameron', 'david cameron',
    'keir starmer',
    'modi', 'narendra modi',
    'trudeau', 'justin trudeau',
    'xi', 'xi jinping',
    // İngilizce - Siyasi Makamlar
    'president', 'vice president',
    'prime minister', 'premier',
    'governor', 'mayors', 'mayor',
    'senator', 'senators',
    'congressman', 'congresswoman',
    'parliament', 'parliamentary',
    'congress', 'congressional',
    'senate', 'senate committee',
    'house of representatives',
    'parliament', 'government', 'administration',
    'cabinet', 'cabinet member',
    'federal', 'state government',
    'diplomat', 'diplomatic',
    'ambassador',
    // İngilizce - Siyasi Konular
    'politics', 'political', 'politician',
    'election', 'elections', 'electoral',
    'campaign', 'political campaign',
    'vote', 'voting', 'voter',
    'policy', 'political policy',
    'legislation', 'legislative',
    'law', 'legal', 'legislation',
    'constitution', 'constitutional',
    'treaty', 'international agreement',
    'sanctions', 'embargo',
    'diplomacy', 'diplomatic',
    // Almanca - Siyasi Liderler
    'kanzler', 'bundeskanzler',
    'scholz', 'olaf scholz',
    'merkel', 'angela merkel',
    'friedrich merz',
    // Almanca - Siyasi Makamlar
    'präsident', 'präsidium',
    'minister', 'bundesminister', 'ministerin',
    'bundesregierung', 'bundesrat', 'bundestag', 'landtag',
    'staatssekreär', 'regierungsprecherin',
    'bundespräsident', 'bundeskanzleramt',
    'senat', 'senatspräsident',
    // Almanca - Siyasi Konular
    'wahl', 'bundestagswahl', 'landtagswahl', 'europawahl',
    'wahlkampf', 'wahlprogramm', 'wahlkampagner',
    'wähler', 'wahlberechtigte', 'wahlgebiet',
    'koalition', 'koalitionsverhandlung', 'koalitionspartner',
    'regierungsbildung', 'regierungserklärung',
    'partei', 'partei',
    'politik', 'politisch', 'politiker', 'politikerin',
    'gesetzgebung', 'gesetzgeber',
    'verfassung', 'verfassungskonzess',
    'referendum', 'volksentscheid',
    'diplomatie', 'diplomatische',
  ],
  Kaza: [
    // Türkçe - Trafik Kazaları
    'kaza', 'kazası', 'kazada', 'kazaya', 'trafik kazası',
    'araç kazası', 'araç çarpışması', 'çarpışma',
    'otobüs kazası', 'otobüs kaza', 'otobüs açısı',
    'kamyon kazası', 'kamyon kaza',
    'trenin kazası', 'tren kazası', 'tren akaryakıtı', 'tren çarpışması',
    'uçak kazası', 'uçak kaza', 'uçak çarpışması',
    'helikopter kazası',
    'gemi kazası', 'gemi çarpışması', 'gemi batması',
    'hızlı tren kazası',
    'teleferik kazası',
    'asansör kazası', 'asansör düşmesi',
    'yaralı', 'yaralılar', 'yaralanan',
    'ölü', 'ölüler', 'ölüm', 'öldü', 'ölen',
    'enkaz', 'enkazda', 'enkazdan',
    'kurtarma', 'kurtarma ekibi', 'kurtarma operasyonu',
    'itfaiye', 'itfaiyeci', 'ambulans',
    'hastaneye kaldırıldı', 'hastaneye başvuru',
    'acil servis', 'acil durum',
    'tıbbi müdahale', 'tıbbi yardım',
    'sahne', 'olay yeri', 'kaza yeri', 'kaza bölgesi',
    'polis', 'polis ekibi', 'polis soruşturması',
    'trafik polisi', 'polis raporu',
    'davul', 'soruşturma', 'tutuklanmıştır', 'gözaltı',
    'alkollü', 'ruhsatsız', 'hız', 'kırmızı', 'işaret ihlali',
    'radar', 'elektronik cihaz',
    'kuru asfalt', 'buzlu yol', 'yağmurlu',
    'şiddetli çatışma', 'çatışma sonucu',
    'can kaybı', 'kayıp', 'mahsur',
    // İngilizce
    'accident', 'accidents', 'accidental',
    'crash', 'crashes', 'crashed',
    'collision', 'collisions',
    'traffic accident', 'traffic incident',
    'car accident', 'vehicle collision',
    'bus crash', 'bus accident',
    'truck accident', 'truck crash',
    'train accident', 'train crash', 'derailment',
    'plane crash', 'airplane crash', 'aircraft accident',
    'helicopter crash',
    'ship accident', 'ship sinking',
    'injured', 'injuries', 'casualties',
    'fatalities', 'deaths', 'deadly',
    'death toll', 'killed', 'died',
    'wreckage', 'debris',
    'rescue', 'rescue team', 'rescue operation', 'rescue effort',
    'fire department', 'ambulance', 'emergency',
    'emergency services', 'emergency response',
    'hospital', 'hospitalized', 'medical attention',
    'scene', 'accident scene', 'crash site',
    'police', 'investigation', 'police investigation',
    'arrest', 'arrest attempted murderer', 'arrested', 'suspects',
    'speeding', 'drunk driving', 'unlicensed', 'violation',
    'weather', 'icy roads', 'rain', 'storm',
    'missing', 'missing persons', 'trapped',
    // Almanca
    'unfall', 'unfälle', 'unfallverlauf',
    'verkehrsunfall', 'verkehrsinzident',
    'autounfall', 'fahrzeugunfall', 'zusammenstoß',
    'busunfall', 'busunglück',
    'lastkraftwagen', 'lastwagencrashs',
    'zugunfall', 'zugzusammenstoß', 'entgleisung',
    'flugzeugunfall', 'flugzeugabsturz', 'flugincident',
    'hubschrauberunfall',
    'schiffunfall', 'schiffbruch',
    'verletzte', 'verletzungen', 'verletzte personen',
    'todesfälle', 'tödlich', 'tote', 'gestorben',
    'todesopfer', 'opfer', 'opferzahl',
    'wrackteile', 'trümmer',
    'rettung', 'rettungsteam', 'rettungsoperation',
    'feuerwehr', 'krankenwagen', 'notfall',
    'notfalldienste', 'notfallreaktion',
    'unfallort', 'unfallschauplatz',
    'polizei', 'polizeiliche ermittlungen',
    'festnahme', 'verhaftet', 'verdächtig',
    'rasen', 'fahren unter alkoholeinfluss', 'unerlaubt',
    'wetter', 'eisige straßen', 'regen', 'sturm',
    'vermisst', 'vermisste personen', 'eingeschlossen',
  ],
  Deprem: [
    // Türkçe - Deprem Genel
    'deprem', 'depremi', 'depremde', 'depremin', 'depremi',
    'zelzele', 'sarsıntı',
    'richter ölçeği', 'richter skalaı',
    'magnitüd', 'şiddet', 'derinlik',
    'aftershock', 'ardışık deprem', 'replica deprem',
    'ön şok', 'ön deprem',
    'merkez', 'deprem merkezi', 'yer merkezleri',
    'epicenter', 'hiposentrum',
    'sismograf', 'sismik', 'sismoloji',
    'jeolog', 'sismolog',
    'fay hattı', 'fay', 'jeolojik fay',
    'tektonik plakalar', 'plaka haritası',
    'volkan', 'volkanik',
    'deprem hasarı', 'hasar', 'hasarları',
    'tasarrufu', 'yapı hasarı', 'ev hasarı',
    'yapı çökmesi', 'çöküntü', 'yıkılmış',
    'enkaz', 'enkazdan kurtarıldı',
    'yaralı', 'yaralılar', 'yaralanmış',
    'ölü', 'ölüler', 'ölüm', 'öldü',
    'kayıp', 'kayıplar', 'mahsup',
    'can kaybı', 'ölüm sayısı',
    'kurtarma', 'kurtarma ekibi', 'kurtarma operasyonu',
    'itfaiye', 'ambulans', 'hastane',
    'sağlık hizmetleri', 'tıbbi yardım',
    'barınak', 'sığınak', 'acil barınma',
    'erzak', 'gıda yardımı', 'yardım',
    'teleferik', 'teleferik kabini',
    'madencilik bölgesinde', 'maden',
    'karayolları', 'yol koparıldı', 'yol hasar',
    'elektrik kesilmesi', 'su kesintisi',
    'gaz kaçağı', 'gaz tesisatı',
    'iletişim kesilmesi', 'haberleşme sorunu',
    'afet', 'afet durumu', 'afet yönetimi',
    'devlet ve kurumlar', 'hükümetin müdahalesi',
    'acil durum', 'acil eylem planı',
    // İngilizce
    'earthquake', 'earthquakes', 'seismic',
    'tremor', 'tremors', 'trembling',
    'richter scale', 'richter magnitude',
    'magnitude', 'seismic magnitude',
    'strength', 'intensity',
    'aftershock', 'foreshock', 'seismic activity',
    'epicenter', 'hypocentre', 'focus',
    'fault line', 'geological fault', 'tectonic fault',
    'tectonic plates', 'plate tectonics',
    'seismology', 'seismologist',
    'damage', 'earthquake damage', 'structural damage',
    'destroyed', 'collapsed', 'collapsed building',
    'wreckage', 'debris', 'ruins',
    'rescue', 'rescue team', 'rescue operation', 'rescue workers',
    'injury', 'injuries', 'injured',
    'death', 'deaths', 'fatalities', 'killed', 'casualties',
    'missing', 'missing persons', 'lost',
    'death toll', 'loss of life',
    'emergency', 'emergency services', 'emergency response',
    'paramedic', 'ambulance', 'hospital', 'medical aid',
    'shelter', 'evacuation', 'evacuated',
    'aid', 'relief', 'humanitarian aid', 'supplies',
    'tsunami', 'tidal wave',
    'volcano', 'volcanic', 'lava',
    'geologist', 'geologists',
    'infrastructure', 'roads damaged', 'collapsed road',
    'power outage', 'power cut', 'blackout',
    'water shortage', 'water cut',
    'gas leak', 'gas pipeline',
    'communication disruption', 'unable to reach',
    'disaster', 'disaster zone', 'disaster response',
    'government intervention', 'government response',
    'state of emergency', 'emergency plan',
    // Almanca
    'erdbeben', 'erdbeben ereignisse',
    'beben', 'erdstoß', 'seismisch',
    'richterskala', 'richterstärke',
    'magnitude', 'richter magnitude',
    'stärke', 'intensität',
    'nachbeben', 'vorbeben', 'seismische aktivität',
    'epizentrum', 'hypozentrum',
    'bruchzone', 'verwerfung', 'tektonische verwerfung',
    'tektonische platten', 'plattentektonik',
    'seismologie', 'seismolog',
    'schaden', 'erdschaden', 'struktureller schaden',
    'zerstört', 'einsturz', 'eingestürztes gebäude',
    'trümmer', 'schutt', 'ruinen',
    'rettung', 'rettungsteam', 'rettungsoperation', 'rettungskräfte',
    'verletzung', 'verletzungen', 'verletzte',
    'tod', 'todesfälle', 'tödlich', 'tote', 'getötet',
    'vermisst', 'vermisste personen', 'verloren',
    'todesopfer', 'verlustrate',
    'notfall', 'notfalldienste', 'notfallreaktion',
    'sanitäter', 'krankenwagen', 'krankenhaus', 'medizinische hilfe',
    'unterkunft', 'evakuierung', 'evakuiert',
    'hilfe', 'katastrophenhilfe', 'humanitäre hilfe', 'lebensmittel',
    'tsunami', 'flutwelle',
    'vulkan', 'vulkanisch', 'lava',
    'geologe', 'geologen',
    'infrastruktur', 'straßenschaden', 'beschädigte straße',
    'stromausfall', 'stromausfallnetz',
    'wassermangel', 'wasserstrom',
    'gasleck', 'gaspipeline',
    'kommunikationsstörung', 'erreichen nicht möglich',
    'katastrophe', 'katastrophenzone', 'katastrophenschutz',
    'regierungseinsatz', 'regierungsreaktion',
    'ausnahmezustand', 'notfallplan',
  ],
};

function inferCategoryFromText(title: string, description: string): ContentCategory {
  const text = `${title} ${description}`.toLowerCase();
  let bestCat: ContentCategory = 'Ekonomi'; // genel haberler için nötr varsayılan
  let bestScore = 0;
  
  // Kategori önceliği: En spesifik kategoriler önce (Kaza/Deprem yüksek, Magazin en düşük)
  const priorityOrder: ContentCategory[] = ['Siyaset', 'Kaza', 'Deprem', 'Spor', 'Saglik', 'Teknoloji', 'Kultur', 'Ekonomi', 'Magazin'];
  
  for (const [cat, keywords] of Object.entries(CATEGORY_KEYWORDS) as [ContentCategory, string[]][]) {
    const score = keywords.filter((kw) => text.includes(kw)).length;
    if (score > bestScore || (score === bestScore && score > 0 && priorityOrder.indexOf(cat as ContentCategory) < priorityOrder.indexOf(bestCat))) {
      bestScore = score;
      bestCat = cat as ContentCategory;
    }
  }
  return bestCat;
}

export function mapToContentCategory(backendCategory?: string, title = '', description = ''): ContentCategory {
  // 'general' ve 'breaking' için metin analizine güven, spesifik kategoriler için haritayı kullan
  if (backendCategory && backendCategory !== 'general' && backendCategory !== 'breaking') {
    return CATEGORY_MAP[backendCategory.toLowerCase()] ?? inferCategoryFromText(title, description);
  }
  return inferCategoryFromText(title, description);
}

function unwrapProxiedImageUrl(input: string): string {
  try {
    const parsed = new URL(input);
    if (parsed.pathname.includes('/api/proxy/image')) {
      const original = parsed.searchParams.get('url');
      if (original) return decodeURIComponent(original);
    }
  } catch {
    // Keep original value when URL parsing fails.
  }
  return input;
}

// Harici CDN resimlerini backend proxy üzerinden yükler (hotlink korumasını aşar)
export function proxyImageUrl(url?: string): string | undefined {
  if (!url) return undefined;

  let upgraded = unwrapProxiedImageUrl(url);

  // BBC images: force larger variants when a size segment exists in URL.
  if (/ichef\.bbci\.co\.uk/i.test(upgraded)) {
    upgraded = upgraded
      .replace(/\/news\/\d+\//i, '/news/1024/')
      .replace(/\/news\/(\d{2,4})x(\d{2,4})\//i, '/news/1024/')
      .replace(/\/ace\/standard\/\d+\//i, '/news/1024/')
      .replace(/\/ace\/ws\/\d+\//i, '/news/1024/')
      .replace(/\/images\/ic\/\d+x\d+\//i, '/images/ic/1024x576/');

    try {
      const parsed = new URL(upgraded);
      const width = Number(parsed.searchParams.get('imwidth') ?? 0);
      if (width && width < 1024) {
        parsed.searchParams.set('imwidth', '1200');
      }
      upgraded = parsed.toString();
    } catch {
      // Keep upgraded URL when parsing fails.
    }
  }

  // Hurriyet: prefer uncropped/original-ish variant when thumbnail path is used.
  if (/image\.hurimg\.com/i.test(upgraded)) {
    upgraded = upgraded.replace(/\/90\/\d+x\d+\//i, '/90/0x0/');
  }

  return `${API_BASE}/api/proxy/image?url=${encodeURIComponent(upgraded)}`;
}

export async function fetchArticles(params: FetchNewsParams = {}): Promise<ApiArticle[]> {
  const query = new URLSearchParams();
  if (params.language) query.set('language', params.language);
  if (params.category) query.set('category', params.category);
  if (params.source) query.set('source', params.source);
  if (params.limit) query.set('limit', String(params.limit));
  if (params.offset) query.set('offset', String(params.offset));

  const res = await fetch(`${API_BASE}/api/news?${query.toString()}`);
  if (!res.ok) throw new Error(`API hatası: ${res.status}`);
  const data: { total: number; articles: ApiArticle[] } = await res.json();
  return data.articles;
}

export async function fetchArticleById(id: string): Promise<ApiArticle> {
  const res = await fetch(`${API_BASE}/api/news/${encodeURIComponent(id)}`);
  if (!res.ok) throw new Error(`API hatası: ${res.status}`);
  return (await res.json()) as ApiArticle;
}

export async function fetchArticleFullContent(id: string): Promise<{ content: string; images?: string[]; fromSource: boolean }> {
  const res = await fetch(`${API_BASE}/api/news/${encodeURIComponent(id)}/full-content`);
  if (!res.ok) throw new Error(`API hatası: ${res.status}`);
  return (await res.json()) as { content: string; images?: string[]; fromSource: boolean };
}
